### ISSUE TITLE
Coordinates table questions

### ISSUE THREAD

**Issue by bmansfeld** [Gabaldonlab/haplotypo#1]
Hey thanks for developing this tool! I am very excited to try to use it.
We have assembled a phased genome and we know that the coordinates are not one-to-one and expect large inversions deletions etc...

I read your advice in the FAQ of the wiki and was hoping you could still offer some advice on how to generate the coordinates table file.

I was thinking using NUCmer and show-coords but not sure exactly how to translate to a format that would work with HaploTypo.

I know this is slightly out of scope for the actual function of the software, but was still hoping you could shed some light on this.

Thanks,
Ben

**Comment by bmansfeld** [comment]
Hi again,
I see that you've made some modifications to address this question.
Could you please shed some light on this question?
Thanks in advance, 
Ben

**Comment by tgabaldon** [comment]
Hi Ben,

Thanks for your interest in our tool and your question. Sorry for our late
response but we were working on some modifications of our script. Your
question arose an interesting point which lead to an improvement of our
pipeline. HaploTypo was not ready to deal with translocations, so we have
modified our pipeline in order to accommodate for this type of complex
variants. This issue is solved from version 1.0.1 and is included in the
FAQS section from GitHub.

Regarding the coordinates table, we think that running NUCmer is a good
approach. Please be aware that our answer is based on our experience as
users, and, probably, there are other (perhaps better) ways of getting the
coordinates. Having said that, we suggest that before running show-coords
you run delta-filter -r -q to filter your alignments, and just keep the
best alignments for each portion of the genome. Afterwards, you can run
show-coords, as you said, to obtain your alignment coordinates. But be
aware that these alignments include INDELs and therefore do not have a
one-to-one correspondence. Therefore, we also suggest that you run a tool
like show-snps to detect INDELs and be able to identify the coordinates in
one haplotype without correspondence in the other. Alternatively, to this
approach, you can run show-aligns, but the output will probably be more
complicated to parse.

Regarding the translation from show-coords to our conversion table format,
right now we do not have an available script that does that for you, so you
would have to generate your own script. Basically you would need a script
that takes the coordinates of the alignment, and prints for EACH POSITION
the corresponding coordinate in the alternative haplotype. Positions
without correspondence in the other HaploType (INDELs), should not be
included in the table, and should be useful for you to get/update the
coordinates of the following line.

Finally, if you prepare a coordinates table for your reference phased
genome and wish to make it available to other users, we will be happy to
host it at the haploTypo’s web site.

Best
HaploTypo team

**Comment by bmansfeld** [comment]
Thanks for the detailed response!
I'm thinking of another way and was curious about your thoughts.
If we treat the two phases as different genome assembly versions, one could potentially use tools developed for "liftovers". 
I'm looking into the CrossMap tool http://crossmap.sourceforge.net/ which is supposed to output coordinates conversion files between assemblies. 

The pipeline I was thinking (or something similar) to use seems to be described here: https://github.com/soybase/crossmap-workflow

Do you have any thoughts on this?
Thanks,
Ben

**Comment by tgabaldon** [comment]
Any method that gives you correct coordinate correspondence between the two
haplotypes will be good. We have no experience with the tool you suggest,
but it seems it will indeed give the information you would need to
reconstruct a coordinate table for haplotypo. Please, if you try it, let us
know how it goes.

The haplotypo team.
