### ISSUE TITLE
Who do I run?

### ISSUE THREAD

**Issue by peflanag** [Gabaldonlab/haplotypo#2]
Hi,

I want to look at some clinical Candida parapsiolosis isolates because I want to make an NxN SNP matrix and MLT. I am use to looking at bacteria and came across this software. I've managed to install it but how do I run? 

As a disclaimer Im not a bioinformatician I'm a microbiologist so self thought command line. Maybe its simple and I am missing sum thing but when I type "HaploTypo.py" to run the whole pipeline what other arguments do I have to put in? I have a reference .fna file but only as one file and not as --hapA and --hapB so I tried --ref with the -f1 and -f2 but it doesn't work and I tried running from the directory my fastq files are in thinking it might just work but it doesn't. I'm just wondering what I am missing and if someone could help? Id really appreciate it!

when I use -ref I get the error "unrecognized arguments"

Cheers,

P

**Comment by vmixao** [comment]
Hi @peflanag,

Thank you for your interest in HaploTypo. This is a pipeline tailored to resolve haplotypes in diploid genomes when a phased reference is available. HaploTypo is divided into four modules, which can be run at once using the _haplotypo.py_ script.

If a phased reference is not available (the case of _C. parapsilosis_), you can use the first two modules of the pipeline (_mapping.py_ and _var_calling.py_, which will do read mapping and variant calling, respectively), but not remaining ones. Therefore, -ref argument is not available in the script _haplotypo.py_. You can find each of these scripts in the _bin/_ directory. If you want to check the arguments available for each of them, you just need to run the script with -h (e.g. _mapping.py -h_).

You can find more details about this pipeline and how to run it in the [manual](https://github.com/Gabaldonlab/haplotypo/blob/master/docs/Haplotypo_manual_v7.pdf).

Please do not hesitate in contacting us if you have other questions.

Best,
Verónica
_On behalf of HaploTypo team_

**Comment by peflanag** [comment]
Hi @vmixao,

Thanks for the reply. Is it possible to make a phased genome from a reference strain? I've not heard of phased genomes until I came across this app. If not, and I run the mapping.py and var_calling.py, will they still produce an aligned fasta file of my isolates so I can run snp-dists on it and run it through RAxML to generate a tree?


Cheers,


P

**Comment by vmixao** [comment]
Hi @peflanag,

A phased genome corresponds to the sequences of the haplotypes of a genome, meaning that, in a diploid, for each chromosome you have the sequences of haplotype A and B. Genome phasing is mostly applied to highly heterozygous genomes, because you need that the sequencing reads span two variants to know that they belong to the same haplotype. Therefore, your ability to phase a sample depends on its level of heterozygosity. However, please be aware that HaploTypo does not perform read-based genome phasing. As explained in our [paper]( https://academic.oup.com/bioinformatics/article/36/8/2569/5675499), HaploTypo resolves variants (i.e. assigns variants to haplotype A or B) when a phased reference is already available.

The _mapping.py_ and _var_calling.py_ scripts do not produce a fasta, but a VCF file with the SNPs of your sample. To obtain a fasta file, you can replace the positions of the reference genome by the respective SNP for each strain. There are programs which can do this for you, such as, for example, GATK FastaReferenceMaker. If you do not include INDELs, you can consider that your fasta files are aligned because all of them will have the same size.


Best,
Verónica
_On behalf of HaploTypo team_

**Comment by peflanag** [comment]
Hi @vmixao cheers for this! I will try it as you say and see how I get on!

Thanks again!
